# Generated by Django 5.0.2 on 2025-01-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(default='django.utils.timezone.now')),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('updated_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('updated_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('Competition_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.IntegerField(default=0)),
                ('score_team2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('ongoing', 'ongoing'), ('finished', 'finished')], default='scheduled', max_length=10)),
                ('scheduled_date', models.DateTimeField(default='django.utils.timezone.now')),
                ('created_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('updated_at', models.DateTimeField(default='django.utils.timezone.now')),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competition.competition')),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='competition.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='competition.team')),
            ],
        ),
    ]
