# Generated by Django 5.0.2 on 2025-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
