# Generated by Django 5.0.2 on 2025-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_competition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
