# Generated by Django 5.0.2 on 2025-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_participant_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
